### ISSUE TITLE
Make Your Layout Responsive for Mobile Devices

### ISSUE THREAD

**Issue by jayco01** [akshaygir15/fem_testimonials_grid_section#1]
I noticed that the website isn’t responsive on smaller screens. On mobile devices, the layout doesn't adjust, which causes the content to overflow or appear too small. To fix this, you need to add a **@media query** to adjust your grid layout for mobile screen sizes.

Here's an example you could add to the bottom of your CSS:

```css
@media (max-width: 768px) {
  .container-main {
    display: flex;
    flex-direction: column;
    align-items: center;
    width: 100%;
    padding: 1rem;
  }

  .box {
    width: 100%;
    margin: 1rem 0;
  }
}
```

This makes the layout stack vertically and ensures that each card fits within the mobile screen. You can also adjust the padding and font sizes as needed.
